### ISSUE TITLE
关于博客的问题

### ISSUE THREAD

**Issue by ououtstanding** [argvchs/hexo-theme-particlex#1]
前端小白来询问
1.load的时候加载不出图片,会有一个损坏的图片的标识
2.评论区可不可以不用登录,因为github时常抽风,登陆成本过大,可能会导致想留言的人放弃
3.侧面的栏位要怎么补充
4.点击和滑动鼠标的时候没有粒子效果

**Comment by argvchs** [comment]
1.loading图片我看一下好像是没push上
2.评论区用的是Gitalk，只能用GitHub登录吧，如果不想用可以把设置调成false，或者按网上的教程换成Disqus等评论系统
3.侧面栏位就是主页的信息卡片啊
4.粒子效果你要自己添加，不自带，看[这篇](https://argvchs.netlify.app/2022/04/17/hexo-blog-3/)

**Comment by argvchs** [comment]
其实 `hexo s` 在本地运行就是类似调试模式了，可以实时修改，不用退出重新 `hexo g` `hexo s`

**Comment by ououtstanding** [comment]
是上传之后，啥都弄完了，然后进入页面，不会显示新内容，得手动f5

**Comment by Heluo1** [comment]
大佬大佬，为什么我的文件部署上去后，about页面没有了，其他页面都有。本地运行没有问题。
这是hexo g --debug的结果
13:50:07.442 DEBUG Rendering HTML post: About/index.html
13:50:07.445 DEBUG Rendering HTML post: tags/index.html
13:50:07.445 DEBUG Rendering HTML post: categories/index.html
13:50:07.445 DEBUG Rendering HTML post: 2022/05/15/hello-world/index.html
13:50:07.446 DEBUG Rendering HTML index: archives/index.html
13:50:07.450 DEBUG Rendering HTML index: archives/2022/index.html
13:50:07.454 DEBUG Rendering HTML index: archives/2022/05/index.html
13:50:07.456 DEBUG Rendering HTML index: index.html
大佬能回一下吗，试了很多方法
