### ISSUE TITLE
评论系统

### ISSUE THREAD

**Issue by cry12138** [argvchs/hexo-theme-particlex#11]
您好，评论系统有办法改吗？比如改成valine的，我自己改了下layout下的script文件，但好像不太行，是还有别的地方吗

**Comment by argvchs** [comment]
评论系统目前只资瓷 Gitalk 啊。。。你可以看 Valine [官方教程](https://valine.js.org/) 自己改

**Comment by cry12138** [comment]
好的吧，谢谢
