### ISSUE TITLE
标签和分类页面不能读取

### ISSUE THREAD

**Issue by kjhuanhao** [argvchs/hexo-theme-particlex#12]
## 网页效果
![](https://cdn.staticaly.com/gh/kjhuanhao/blogcdn@master/img/Snipaste_2022-09-05_11-31-41.png)

## 文章标签设置正常
![](https://cdn.staticaly.com/gh/kjhuanhao/blogcdn@master/img/Snipaste_2022-09-05_11-35-59.png)

## 标签type设置
![](https://cdn.staticaly.com/gh/kjhuanhao/blogcdn@master/img/Snipaste_2022-09-05_11-36-39.png)

**Comment by kjhuanhao** [comment]
## 标签设置没问题，单独标签可以显示，就是标签页不可以正常显示
![](https://cdn.staticaly.com/gh/kjhuanhao/blogcdn@master/img/Snipaste_2022-09-05_11-38-15.png)

**Comment by argvchs** [comment]
`title` 也要改一下。。（好像 `type` 并没有什么用？？

```markdown
---
title: tags
date: 20xx-xx-xx xx:xx:xx
type: "tags"
---
```
