### ISSUE TITLE
请问怎么把跳转时的loading页面关掉?

### ISSUE THREAD

**Issue by doraam** [argvchs/hexo-theme-particlex#13]

**Comment by argvchs** [comment]
可以关，注释掉 `themes/particlex/layout/layout.ejs` 中的 loading 即可
![image](https://user-images.githubusercontent.com/64528288/188468055-8902b69a-dd00-4780-93b5-55792ad69734.png)
但这样会有报错，如果不想要报错，还要修改 `themes/particlex/source/js/particlex.js`
![image](https://user-images.githubusercontent.com/64528288/188468681-44c7a20e-b142-463b-81d1-69aac43db8ee.png)

（。。。其实不建议关掉 loading，关掉 loading 可能会出现如下情况
![image](https://user-images.githubusercontent.com/64528288/188469366-31a7da46-c0ba-495a-bb62-7eaeba439ece.png)

**Comment by wzdc** [comment]
改成DOMContentLoaded会不会好点呢？

**Comment by wzdc** [comment]
> 可以关，注解掉`themes/particlex/layout/layout.ejs`中的loading即可以 但这样会有报错，如果不想报错，还要修改 ![图片](https://user-images.githubusercontent.com/64528288/188468055-8902b69a-dd00-4780-93b5-55792ad69734.png)`themes/particlex/source/js/particlex.js` ![图片](https://user-images.githubusercontent.com/64528288/188468681-44c7a20e-b142-463b-81d1-69aac43db8ee.png)
> 
> （。。。其实际上不建议关闭loading，关闭loading 可能会出现如下情况 ![图片](https://user-images.githubusercontent.com/64528288/188469366-31a7da46-c0ba-495a-bb62-7eaeba439ece.png)

改成DOMContentLoaded会不会好点呢？

**Comment by argvchs** [comment]
DOMContentLoaded 只是 DOM 结构加载完成，并没有完成全部的渲染啊（如 LaTeX，Highlight，评论等）

**Comment by wzdc** [comment]
`load` 要等文章的图片和视频加载完成才会显示（不知道用户有没有耐心等他加载完成）
