### ISSUE TITLE
gitalk 报错not found

### ISSUE THREAD

**Issue by GuoShuaiGO** [argvchs/hexo-theme-particlex#14]
![image](https://user-images.githubusercontent.com/94844998/189518767-86bc0d4b-4e4c-4912-8b0e-2b3c9262255f.png)

**Comment by GuoShuaiGO** [comment]
提示需要需要初始化，如何初始化呢？

**Comment by GuoShuaiGO** [comment]
哦，我解决了它，管理员initialize时需要科学上网

**Comment by argvchs** [comment]
。。
