### ISSUE TITLE
Please Help Me!!

### ISSUE THREAD

**Issue by Martin-share** [argvchs/hexo-theme-particlex#17]
![image](https://user-images.githubusercontent.com/93062634/190414546-b0fe7888-750a-45ec-a4e1-2e8fc04a8ce3.png)
![image](https://user-images.githubusercontent.com/93062634/190414756-13a721fc-97c3-4b23-b600-a8edbe33b6b3.png)
Modify which code under the folder can customize your name, etc.

**Comment by argvchs** [comment]
`_config.yml`
