### ISSUE TITLE
使用加速後會卡在Loding頁面

### ISSUE THREAD

**Issue by Arcelibs** [argvchs/hexo-theme-particlex#19]
用github pages是正常的 
https://arcelibs.github.io/blog-hexot01/

(我是github pro會員，所以用private專案+github pages)

但是改了netlify加速後就會卡在loding頁，這跟我用private專案會是有關的嗎
https://arceblog.netlify.app/

![image](https://user-images.githubusercontent.com/49543451/190680194-2bc34f8b-ba43-4f98-8d1d-6ff0d97413ff.png)

**Comment by argvchs** [comment]
应该是吧。。Netlify 可能无法完全访问 Private 仓库
