### ISSUE TITLE
一些小反馈

### ISSUE THREAD

**Issue by iiishop** [argvchs/hexo-theme-particlex#25]
配置了有一段时间了，感觉是一款界面非常舒适美观的主题，对我感官的第一印象就非常不错。现希望能有一些新的功能的支持。

1. 希望能加入对mermaid和latex的支持。有时候会有撰写这些内容的需要，但无法在主题上呈现。尝试自主配置了mermaid，但之后网页一直停留在载入界面。希望能得到原生的支持

2. 在使用了category后，主题的category页面无法自动显示现有的category，需要在category的index中主动添加链接。希望能得到更新修复。

**Comment by iiishop** [comment]
您好，Latex已经参考您的博客配置成功了，这块已经无需再麻烦您了。

**Comment by argvchs** [comment]
Mermaid 的语法是用一个代码块括起来，用和代码高亮的一样的方式动态渲染，也许可以 ~~但我忒弱了不会啊~~
但如果要和 LaTeX 一样，在编译期预处理内容，主题是不能直接做的，要处理也比较麻烦
。。

**Comment by iiishop** [comment]
您好，今天尝试了按照网上的方法配置了mermaid，版本号为9.1.7 ，使用的 [hexo-filter-mermaid-diagrams](https://github.com/webappdevelp/hexo-filter-mermaid-diagrams#hexo-filter-mermaid-diagrams) 插件。
若语法错误时，网页页面可以显示，并且代码块显示语法错误；但若为正确配置，则进入含有mermaid的推文就一直卡在loading页面。
在网络上找寻了数小时没有找到解决方案，请问能否推出一期教程来教学配置mermaid。
万分感谢。

**Comment by argvchs** [comment]
今天翻看着 [Issues](https://github.com/argvchs/hexo-theme-particlex/issues) 突然想到好像还有一个 Mermaid 的问题

> 看来是换成兼容好的 NexT 了？
>
> <img width="610" alt="image" src="https://user-images.githubusercontent.com/64528288/211043676-b50e1f0e-d3b1-4bf3-b815-3788fd0b241b.png">

卡住应该是因为 Mermaid 和 Highlight.js 都处理了 `<pre>` 标签

所以在 [`functions.js#L7`](https://github.com/argvchs/hexo-theme-particlex/blob/master/source/js/functions.js#L7) 后面加上一行

```js
if (lang == "mermaid") continue;
```

应该就可以了？

**Comment by argvchs** [comment]
> 在使用了category后，主题的category页面无法自动显示现有的category，需要在category的index中主动添加链接。希望能得到更新修复。

可以显示现有的 Category 啊。。（有渐变色的是当前选中的）

<img width="715" alt="image" src="https://user-images.githubusercontent.com/64528288/211132284-08bccdb0-d859-4767-a71b-4fbdf931a3aa.png">

还有，Category 的 Index 是？？？

**Comment by argvchs** [comment]
可能是之前用 `<%- rootlink %>categories/<%- category.name %>` 获取的链接不准确吧

现在改成 `<%- url_for(category.path) %>` 了
