### ISSUE TITLE
请问如何自定义使用网络字体？

### ISSUE THREAD

**Issue by LynxCatTheThird** [argvchs/hexo-theme-particlex#3]
前端小白前来求教：
因为GitHub实在太慢，内置字体又太大，所以我把内置字体全部删除，又将字体全部改为“等线”，但这样又会面临外观问题和兼容问题，因此我就萌发了使用网络字体的念头。请问我该如何配置？

**Comment by argvchs** [comment]
有以下几个方案

1. 部署博客到 Vercel/Netlify
   看这篇 <https://argvchs.netlify.app/2022/04/17/hexo-blog-4/>
2. 使用网络字体
   可以用[Google Fonts](https://fonts.google.com/)啊（但速度。。
   在 Google Fonts 上选择一些字体，右边会看到一个已选择字体栏，将里面的 HTML 复制到 layout.ejs 上，同时把 particlex.css 的字体名称更改
   `"Poppins"`：英文字体
   `"Noto Sans SC"`：中文字体
   `"Fira Code"`：等宽字体
   Google Fonts 就不多说了，重点是加速问题
   一个有效的办法是把你刚刚引入的 CSS 文件下载下来， 会看到很多（真的很多）字体文件，全部下载下来
   最好用正则选出所有文件路径，然后用下载器（比如 [Xdown](https://xdown.org)）下载，这样能自动组合好文件目录，替换 CSS 中的网址即可
3. 使用 Variable Font
   Variable Font 我不是很清楚，听说体积会小一点，自己查一下

**Comment by LynxCatTheThird** [comment]
新添加的Variable Font真不错，拿它来引用本地.ttf也很好，谢谢

**Comment by argvchs** [comment]
额。其实Variable Font一个文件太大（12M+）（尤其中文字体），加载可能会慢一些
原来的静态字体文件字符分区成许多小文件，加载的内容≤总大小，所以现在中文字体改回了原来的静态字体
如果要全用可变字体，有一个`-test`文件夹（前面有一个减号），是之前的内容 ~~也可以不更新~~
