### ISSUE TITLE
加入搜索功能的问题

### ISSUE THREAD

**Issue by SDA2333** [argvchs/hexo-theme-particlex#34]
可以对那个搜索功能的添加详细说一下吗，整了好久都没显示

**Comment by argvchs** [comment]
？直接 `enable: true` 就可以了

**Comment by argvchs** [comment]
刚更新了，现在不自带搜索 ~~因为自带没人装扩展~~

**Comment by argvchs** [comment]
是 URL 解析出错了，见 https://github.com/argvchs/hexo-theme-particlex/issues/37#issuecomment-1345467015
