### ISSUE TITLE
首页无了

### ISSUE THREAD

**Issue by LynxCatTheThird** [argvchs/hexo-theme-particlex#35]
posts里有东西，但首页上啥都没有。。。

![image](https://user-images.githubusercontent.com/103188954/206607260-574768d8-f272-4cd4-a531-3da86662fa1f.png)

![image](https://user-images.githubusercontent.com/103188954/206607405-a54944ba-8aa1-4bb2-95ac-101c6d2d5606.png)

**Comment by argvchs** [comment]
？？？？？？？？？

**Comment by LynxCatTheThird** [comment]
您也不知道吗？我也不知道我做了啥。。。

看来只好一个一个替换回您原来的文件了。。。。

**Comment by argvchs** [comment]
。。。
不用替换吧，重新 Clone（把原来的改成 `particlex-old`），把修改地方改一下就行了

**Comment by LynxCatTheThird** [comment]
额，似乎是posts.ejs出了问题。反正这个没改过，那就替换着吧。以后不作。叨扰了。
