### ISSUE TITLE
搜索死活不生效

### ISSUE THREAD

**Issue by LynxCatTheThird** [argvchs/hexo-theme-particlex#37]
在搜索框中输入“物理”，死活不出结果，经检查是因为：
![image](https://user-images.githubusercontent.com/103188954/206854690-a484b891-ce27-41fd-97e8-75f559af055e.png)
这个怎么办？
config在https://github.com/LynxCatTheThird/hexo-new

**Comment by argvchs** [comment]
安装插件啊。。

**Comment by argvchs** [comment]
```bash
npm i hexo-generator-search-lite -S
```

**Comment by argvchs** [comment]
啊啊啊啊啊想起来还要添加 `optimize: true`，在根目录的 `config` 里

```yaml
search:
    optimize: true
```

**Comment by LynxCatTheThird** [comment]
![image](https://user-images.githubusercontent.com/103188954/206879930-0475fc87-f67a-4ab5-824f-8cb5074d8439.png)
![image](https://user-images.githubusercontent.com/103188954/206879934-0ff0fae2-74fa-4bc6-9f99-11282cd51ecd.png)
![image](https://user-images.githubusercontent.com/103188954/206879935-a5ba3335-5a7e-499e-ae6f-4c3a82746c95.png)
optimize: true后确实生效了。

但是如果先搜“站务”，打掉后再搜“物理”，分类是“物理”的那篇文章就搜不出来。

**Comment by LynxCatTheThird** [comment]
而且“站务”下有三篇文章：_HelloWorld 、图床测试（图床测试是加密的，存档里可以看到）、Markdown 和 LaTeX 测试_，搜索的话只搜出来 _HelloWorld 和 Markdown_ ，没有图床。

**Comment by LynxCatTheThird** [comment]
更新了一下_searcher.js_，无明显变化。而且好像只能搜到Helloworld和Markdown两篇文章，把《人对地面的压力》里的“人对”复制粘贴进去都不出结果。。。

**Comment by argvchs** [comment]
> ![image](https://user-images.githubusercontent.com/103188954/206879930-0475fc87-f67a-4ab5-824f-8cb5074d8439.png)

？？？？？？？？？
这是搜索格式。。。而且搜索数据是自动生成

还有，主题 `config` 要更新一下

```yaml
search:
    enable: true
    path: /search.json
```

实在不行搜不到的话 `hexo cl` 清空缓存再 `hexo s`

**Comment by LynxCatTheThird** [comment]
![image](https://user-images.githubusercontent.com/103188954/206888127-0011aa62-4795-4ba2-8821-343121df6277.png)
![image](https://user-images.githubusercontent.com/103188954/206888137-940ce3a2-96ad-46d0-b1e6-d26fcd348549.png)
还是一样

**Comment by LynxCatTheThird** [comment]
不如我再替换一次文件？

**Comment by LynxCatTheThird** [comment]
![image](https://user-images.githubusercontent.com/103188954/206888611-cad5d4ad-db98-4977-b32c-0cd0769889cb.png)
好像只有第一个和最后一个能生效？

**Comment by argvchs** [comment]
啊，是因为 URL 有中文

![image](https://user-images.githubusercontent.com/64528288/206888719-95afc6eb-25c4-49d4-a5d5-545ff73485eb.png)

是根据 `path` 来标识每个文章的，HTML 里的 `path` 被解析了但是 `search.json` 里的没有，所以对应不上
插件已经用 `encodeURI` 修复了

```bash
npm i hexo-generator-search-lite -S
```

**Comment by argvchs** [comment]
~~我怎么可以正常搜索？~~

<img src="https://user-images.githubusercontent.com/64528288/206889084-64b052c1-7a62-40dd-9257-b97bcde10e77.png" width="500">

其实文件名和标题不一定对应。。Permalink `:year/:month/:day/:title/` 里的最后的标题其实应该是去掉 `.md` 后缀的文件名

**Comment by LynxCatTheThird** [comment]
![image](https://user-images.githubusercontent.com/103188954/206891188-2c669b8a-ee61-4c34-b8ea-b9aebdb5326e.png)
确实成功了
