### ISSUE TITLE
多行公式

### ISSUE THREAD

**Issue by Tiagim** [argvchs/hexo-theme-particlex#39]
这样写不对吗？
[tp](https://cdn.luogu.com.cn/upload/image_hosting/nfuznrb2.png)

**Comment by argvchs** [comment]
MathJax 可能确实无法换行（但是 `\begin{aligned}` 中可以？）

解决方法是改成 `KaTeX`。。。

```ejs
<!-- layout.ejs, insert after line 41 -->
<link rel="stylesheet" href="https://cdn.staticfile.org/KaTeX/0.16.4/katex.min.css">
<script src="https://cdn.staticfile.org/KaTeX/0.16.4/katex.min.js"></script>
<script src="https://cdn.staticfile.org/KaTeX/0.16.4/contrib/auto-render.min.js"></script>
```

```js
// particlex.js, insert after line 24
renderMathInElement(document.body);
```

```js
// crypto.js, insert after line 40
renderMathInElement(document.body);
```

然后在 Blog 根目录运行：

```bash
npm un hexo-filter-mathjax -S
hexo cl
hexo s
```

如果想禁止复制 KaTeX ~~（因为我觉得复制可能显得很乱。。）~~

```css
/* particlex.css, replace line 306 */
iframe, .math {
```

**Comment by Mizoreeeee** [comment]
![image](https://github.com/theme-particlex/hexo-theme-particlex/assets/77111118/d4cbd2f4-37c7-439c-bc3c-157175fef07d)
![image](https://github.com/theme-particlex/hexo-theme-particlex/assets/77111118/9e57b3fb-77db-4475-b244-f9793976601f)
![image](https://github.com/theme-particlex/hexo-theme-particlex/assets/77111118/139f640a-345f-43ff-93d1-b1e88d1ab973)
![image](https://github.com/theme-particlex/hexo-theme-particlex/assets/77111118/cb0d43a2-66ad-45a6-9135-6c42eb99a935)
已经启用`KaTeX`了，为什么还是无法换行？

**Comment by Mizoreeeee** [comment]
网上看到有说`KaTeX`不支持align的，换成aligned也是一样的效果

**Comment by LeventureQys** [comment]
解决了吗，似乎目前还是有这个问题，不能渲染块状katex公式
