### ISSUE TITLE
头一次对一个主题这么上心，麻烦您了

### ISSUE THREAD

**Issue by LynxCatTheThird** [argvchs/hexo-theme-particlex#4]
关于 CSS 的几个问题：
1. 如图，联系方式图标有亿点点多，都放不开了，怎么样把这个侧栏调宽？
![image](https://user-images.githubusercontent.com/103188954/180447795-ff45a0d3-1e78-4a6f-865d-d1e88bc2a740.png)
2. 如图，谷歌字体加载不正常
![image](https://user-images.githubusercontent.com/103188954/180448312-88bdfee2-987b-499b-b82d-80691f55363b.png)
C:\Users\Administrator\hexo\home\themes\particlex\source\css\fonts.min.css内容：
![image](https://user-images.githubusercontent.com/103188954/180448772-1b713750-3d5d-4dd8-9801-f43af4eba9c6.png)
C:\Users\Administrator\hexo\home\themes\particlex\source\css\particlex.css内容：
![image](https://user-images.githubusercontent.com/103188954/180448816-0f8412d3-391d-44ed-bb7f-0c0cf8143812.png)

**Comment by argvchs** [comment]
1. 侧栏~~你放十个就整齐了~~，少放一点，其他写在about里面
2. CSS里面怎么有HTML标签？把你fonts.min.css的内容放到layout.ejs里面。或者这样
   ![image](https://user-images.githubusercontent.com/64528288/180458893-9c925f8d-26a5-42e5-aae5-0aa63beac47e.png)
   用CSS3 import的方式导入，不用添加HTML，那么你的fonts.min.css应该是这样（没有`<style>`）
   ```css
   @import url('https://fonts.googleapis.com/css2?family=Edu+TAS+Beginner:wght@600&family=Ma+Shan+Zheng&display=swap');
   ```

**Comment by LynxCatTheThird** [comment]
还是不行[大哭]
![image](https://user-images.githubusercontent.com/103188954/180592752-74fe2b34-62e5-435d-b94e-610fddeadfa9.png)

**Comment by argvchs** [comment]
？？
import不行就直接用`<link>`标签（写在layout.ejs的`<head>`里）：
```
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Edu+TAS+Beginner:wght@400..700&family=Ma+Shan+Zheng&display=swap">
```
particlex.css的字体要替换一下（不是test里的）
把`"Poppins","Noto Sans SC",sans-serif`替换成`"Edu TAS Beginner","Ma Shan Zheng",cursive`

还有主题的_config.yml要改一下，`vf_fonts_enable`设为`false`

**Comment by LynxCatTheThird** [comment]
还是不行(大哭)
![Screenshot_2022-08-10-22-00-20-86](https://user-images.githubusercontent.com/103188954/183921860-52d63e02-906f-4ceb-bd91-80ca8dc3599f.png)

**Comment by korilin** [comment]
侧边卡片宽度写死了 300px，如果希望增大这个卡片的宽度，可以在主题的 layout/card.ejs 下面修改这个宽度

**Comment by argvchs** [comment]
先 %%% stO @korilin Orz
~~但他好像在问字体a~~
@LynxCatTheThird
你想，googleapis的网址，手机上当然打不开（当然你可以挂🪜）
用这个打包好的字体文件：[font.zip](https://github.com/argvchs/hexo-theme-particlex/files/9398811/gfonts-helper.zip)
解压到 `theme\particlex\source\css` 文件夹，替换默认字体
如果你还要写代码，用这个：[font.zip](https://github.com/argvchs/hexo-theme-particlex/files/9398876/gfonts-helper.zip)

**Comment by leolyx54110** [comment]
@argvchs 大佬你发的这个字体包具体都有那些字体哦。wttf的字体预览不了。然后名称也是乱的

**Comment by argvchs** [comment]
~是 woff2 不是 wttf~
字体就是 Edu TAS Beginner 和 Ma Shan Zheng
woff2 是网络字体当然预览不了啊。。
名称乱了？我用的是 GoogleFonts 的 API，下载下来就是这样

**Comment by argvchs** [comment]
@LynxCatTheThird
或者你先重装主题？
> 删掉 `themes/particlex` 文件夹（把主题 config 移到其他地方），重新 Clone 主题，复制回原来的配置
不要放弃啊

**Comment by leolyx54110** [comment]
@argvchs 好的。感谢

**Comment by argvchs** [comment]
@LynxCatTheThird
人呢？？根据你页面修改的地方重写了一份 blog

![image](https://user-images.githubusercontent.com/64528288/188314187-4bb575c8-c56a-4008-a041-4f319a03780d.png)
![image](https://user-images.githubusercontent.com/64528288/188314209-b6afb420-b374-45e2-89ac-d330828d86ed.png)

邀请：<https://github.com/argvchs/lynxcatthethird/invitations>
是私有库需要邀请才可以访问，注意 git 一定要设置用户名（[here](https://argvchs.netlify.app/2022/04/17/hexo-blog-4/)）
用以下命令 clone 下来即可
```bash
git clone git@github.com:argvchs/lynxcatthethird.git
```
或者你没有 SSH
```bash
git clone https://github.com/argvchs/lynxcatthethird.git
```

然后安装
```bash
cd lynxcatthethird
npm install
```
运行完之后会在你刚才运行的目录下生成 `lynxcatthethird` 文件夹，文件夹名称可以自行修改
注意要删掉里面的 `.git` 文件夹，默认隐藏了，要显示隐藏文件才能看到
> 应该要删吧，其实不删也可以？？我不道啊

还有一个，就是你看站点的 `_config.yml`，`deploy` 部署参数链接我写的 HTTPS，如果有 SSH 可以改一下
然后就可以愉快的使用啦\~ （。。。

**Comment by LynxCatTheThird** [comment]
~~张大夫妙手之死人复活~~ 我回来了。。。

前段时间 C++ 占据了大多数编程时间， ~~都忘了还开着这个 issues 了~~ ，所以一直没回。最近由于需要重拾 Hexo ，这才发现这里还有个佬苦苦等着我。

话说那个问题，已经解决了，方法是

```bat
rd /s /q C:\Users\LynxCatTheThird\web\person\themes\particlex\source\css\fonts
del /f /s /q C:\Users\LynxCatTheThird\web\person\themes\particlex\source\css\fonts.min.css
```

不用字体了，让您见笑了

**Comment by argvchs** [comment]
额
好吧
