### ISSUE TITLE
升级过后，所有的代码块都变成了text

### ISSUE THREAD

**Issue by Yuzi0201** [argvchs/hexo-theme-particlex#42]
9月份的还是正常的，更新后所有都是text，hexo也更新了，求解
![image](https://user-images.githubusercontent.com/50757904/208299032-0c576739-3fd5-41ba-be4a-a261730a99e4.png)

**Comment by Yuzi0201** [comment]
仔细看了下逻辑，作者的博客的</pre>是这样的：
![image](https://user-images.githubusercontent.com/50757904/208300708-482c0d2b-f929-463c-85c5-250dec679507.png)
而我的是这样：
![image](https://user-images.githubusercontent.com/50757904/208300723-de391f40-fd7d-410e-b686-1b12dfc0af68.png)
然后检测语言是直接取pre上的class，而我的pre没有class，正在继续排查原因中……
![image](https://user-images.githubusercontent.com/50757904/208300777-000b0739-e2b6-4225-b214-56b2df19fd33.png)

**Comment by Yuzi0201** [comment]
看了一下，生成的HTML都不一样了，难道是hexo的变化？

**Comment by argvchs** [comment]
是因为用了 Pandoc。。

**Comment by Yuzi0201** [comment]
> 是因为用了 Pandoc。。

所以该怎么配置捏

**Comment by argvchs** [comment]
<https://argvchs.netlify.app/2022/06/17/hexo-latex/>

这里

**Comment by argvchs** [comment]
好像可以 ~~直接改 README 让所有人都用 Pandoc 就不用处理兼容了~~？

**Comment by Yuzi0201** [comment]
那是否应该给主题一个开关？不然不使用这个Pandoc的人就会出现bug啊

**Comment by Yuzi0201** [comment]
> 好像可以 ~直接改 README 让所有人都用 Pandoc 就不用处理兼容了~？

噗，也行，不过不太好罢

**Comment by argvchs** [comment]
。。

**Comment by argvchs** [comment]
好像检测 `firstChild.classList` 就都可以了
