### ISSUE TITLE
运行hexo g之后出现的问题

### ISSUE THREAD

**Issue by K0max** [argvchs/hexo-theme-particlex#49]
![image](https://user-images.githubusercontent.com/100927897/212444672-ad7f0d1a-dd68-4521-8f4c-8103ddbb63ae.png)

gitpage是我的root文件夹

仅进行了README.md里提到的操作。生成的public的index.html是空文件

**Comment by argvchs** [comment]
？

**Comment by argvchs** [comment]
如果 iconLinks 为空后面必须要有一个 `{}`

```yaml
iconLinks:
    {}
```
