### ISSUE TITLE
新建页面(new page)没有评论功能

### ISSUE THREAD

**Issue by wzdc** [argvchs/hexo-theme-particlex#50]
新建友联页面没有评论功能，只有文章有

**Comment by argvchs** [comment]
默认就是这样啊。。

**Comment by argvchs** [comment]
可以调整 [`script.ejs`](https://github.com/argvchs/hexo-theme-particlex/blob/master/layout/script.ejs#L3)

**Comment by wzdc** [comment]
要怎么操作

**Comment by argvchs** [comment]
更新了。。。但是改动有点多（因为还优化了其他的一些东西）

以下是解决 `hexo new page` 没有评论问题的更改

`layout.ejs`

```diff
- <%- include("script") %>
+ <%- partial("script", { type: layout }) %>
```

`script.ejs`

```diff
- <% if (is_post()) { %>
+ <% if (type == "post") { %>
```
