### ISSUE TITLE
代码块显示有问题

### ISSUE THREAD

**Issue by IceOfSummer** [argvchs/hexo-theme-particlex#61]
![image](https://xds.asia/public/GithubIssue/2023-2-6-94aa08a7-cdfe-42de-8c66-9f29c329567f.png)

换回默认主题可以正常显示。

好像所有的代码块都有问题。。。

**Comment by IceOfSummer** [comment]
抱歉 没有看之前的issue

**Comment by argvchs** [comment]
README 里就有提到啊

https://github.com/argvchs/hexo-theme-particlex/blob/aa82f129f738caa543a46f67a436cad5197dc657/README.md#L32-L49

**Comment by IceOfSummer** [comment]
> README 里就有提到啊
> 
> https://github.com/argvchs/hexo-theme-particlex/blob/aa82f129f738caa543a46f67a436cad5197dc657/README.md#L32-L49

我以为这个是非必须的(虽然写了不兼容)。。 🥲
