### ISSUE TITLE
代码框与代码高亮失效

### ISSUE THREAD

**Issue by LynxCatTheThird** [argvchs/hexo-theme-particlex#65]
最近尝试着将更新至最新版，随后发现代码框不正常，代码高亮故障。

---

### C++

Markdown源代码为

```` Markdown
xxxxxxxxxxxx

``` cpp
#include<iostream>
using namespace std;
int main{
    int n;
    cin>>n;
    cout<<n;
    return 0;
}
```

xxxxxxxxxxxx
````

渲染后，语言标签与复制按钮消失（无相关元素），部分代码丢失，语言标签“Cpp”跑到了代码框内。效果为：

![image](https://user-images.githubusercontent.com/103188954/226081474-aa5bc73d-6f5c-4be8-885f-9fb6498ad583.png)

---

### HTML

Markdown源代码为

```` Markdown
如有可能，请将您的信息格式化为如下格式（尽可能保留各行前的 12 个空格）：

``` HTML
         <div class="card">
            <img class="ava" src="头像" />
            <div class="card-header">
               <div>
                  <a href="链接">昵称</a>
               </div>
               <div class="info">签名</div>
            </div>
         </div>
```

同时奉上本站信息：
````

渲染后，大部分代码丢失，但复制按钮却仍然可以复制到全部代码。效果为：

![image](https://user-images.githubusercontent.com/103188954/226081995-4bb3e9cc-4f71-43dd-bb19-4740840f28c6.png)

---

### 一些可能有用的信息

1. 似乎不是渲染器的问题。我尝试将渲染器从 `[hexo-renderer-markdown-it](https://github.com/hexojs/hexo-renderer-markdown-it)` 换到 `[hexo-renderer-marked](https://github.com/hexojs/hexo-renderer-marked)`，并无作用
2. Hexo 自带的高亮已停用
3. `Highlight.js` 加载似乎无异常
4. Config 在 [https://github.com/LynxCatTheThird/web-new/](https://github.com/LynxCatTheThird/web-new/)

**Comment by LynxCatTheThird** [comment]
![image](https://user-images.githubusercontent.com/103188954/226082418-57a5bc9e-a21d-4752-be60-5c2a7001f052.png)

![image](https://user-images.githubusercontent.com/103188954/226082429-90a5524a-30c0-436d-9324-5293f646b8fd.png)

刚才看了看 `hexo g` 出来的 HTML，似乎并无异常。

**Comment by argvchs** [comment]
不要用 MarkdownIt 啊
MarkdownIt 无法渲染 LaTeX

**Comment by argvchs** [comment]
> 渲染后，语言标签与复制按钮消失（无相关元素），部分代码丢失，语言标签“Cpp”跑到了代码框内

但是。。

我这里新建了一个博客然后安装主题，渲染非常正常
应该是你更新不对

![image](https://user-images.githubusercontent.com/64528288/226085807-6878b710-1b34-4fc1-b050-9731fed01ac1.png)

**Comment by argvchs** [comment]
最新版应该是 v2.5.5，你是不是用的 v2.5.4 有这个问题

https://github.com/argvchs/hexo-theme-particlex/blob/d8332bbd1dab8253317dde2cbfdc84985cf2c23e/package.json#L3

**Comment by LynxCatTheThird** [comment]
我想我可以尝试一下用未经修改的主题试试……
