### ISSUE TITLE
手机端访问页面时显示不全

### ISSUE THREAD

**Issue by CalciumSilicate** [argvchs/hexo-theme-particlex#70]

**Comment by argvchs** [comment]
什么不全？

**Comment by CalciumSilicate** [comment]
![Screenshot_2023-04-02-18-21-23-609_com.android.browser.jpg](https://user-images.githubusercontent.com/61231989/229347172-5d7d5bf1-53b3-4fec-9b36-ea64aff8ac43.jpg)

![Screenshot_2023-04-02-18-21-39-790_com.android.browser.jpg](https://user-images.githubusercontent.com/61231989/229347174-75cc7294-54fd-48b3-a01e-19800a886b65.jpg)

屏幕的右边缘显示不全

**Comment by CalciumSilicate** [comment]
不能左右拖动😢

**Comment by argvchs** [comment]
<img width="272" alt="image" src="https://user-images.githubusercontent.com/64528288/229354726-79e1e3a3-67ea-42bf-b1a7-2202e813b925.png">

终于修好了，上次大重构（）的时候没注意到，变成这样了
更新主题吧
