### ISSUE TITLE
文章图片不显示

### ISSUE THREAD

**Issue by K1nako0** [argvchs/hexo-theme-particlex#72]
![image](https://user-images.githubusercontent.com/105909793/233124132-28f57322-c49d-461e-8037-d5ea49f2fe46.png)

上面是直接贴url，下面是添加的超链接，都没有显示图片，图床能正常访问

![image](https://user-images.githubusercontent.com/105909793/233124556-09ce8177-9ca8-4983-a84a-64b28d710390.png)
md文件编辑是这样，求解答

**Comment by argvchs** [comment]
格式应该是这样吧。。。
要在前面添加一个 `!`

```markdown
![image](image.png)
```
