### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by K1nako0** [argvchs/hexo-theme-particlex#73]
不显示emoji怎么办啊
![QQ截图20230424223541](https://user-images.githubusercontent.com/105909793/234029345-916829ee-4c95-46e6-8f20-d96ab30a54b6.png)
成这样了

**Comment by argvchs** [comment]
？

**Comment by K1nako0** [comment]
尝试换渲染引擎hexo-renderer-markdown-it，能显示，但是代码编辑器就不兼容了，然后就换回原本的渲染引擎

**Comment by argvchs** [comment]
我试一下

**Comment by argvchs** [comment]
<img width="37" alt="image" src="https://user-images.githubusercontent.com/64528288/234039012-20ec09a3-d765-4ab0-b978-74a8e7d5f85f.png">

确实是渲染器问题啊，只要不是 Marked 都可以

**Comment by argvchs** [comment]
啊，可以用 Pandoc
这一篇：http://argvchs.github.io/2022/06/17/hexo-latex/
把 LaTeX 的内容去掉就可以了

**Comment by K1nako0** [comment]
这个编辑器不兼容有什么办法吗，这是渲染器hexo-renderer-markdown-it-plus的配置文件
![QQ截图20230424233603](https://user-images.githubusercontent.com/105909793/234045838-2deb9e4a-0b84-4285-a124-0ce457e3f627.png)
