### ISSUE TITLE
关于icon_links的使用

### ISSUE THREAD

**Issue by KeepTheFear** [argvchs/hexo-theme-particlex#8]
icon_links里面的 name 和 theme 怎么填鸭。。。

**Comment by argvchs** [comment]
从 <https://fontawesome.com/search> 找图标（只能选 soild 和 brands 两种格式）
例如：
![image](https://user-images.githubusercontent.com/64528288/186051366-a684a7a2-e183-449b-9f7c-5ab19ad47817.png)
`name` 就是 0，`theme` 就是 soild

**Comment by 70loKirin** [comment]
请问GitHub图标是branchs，你的页面是怎么添加的GitHub的图标的呢

**Comment by YluHuu** [comment]
你好，请问一下具体格式可以发一下吗，还是有点迷糊

**Comment by qllokirin** [comment]
> 你好，请问一下具体格式可以发一下吗，还是有点迷糊

    icon_links:
        # []
        # Example:
        # <name>:
        #    name: <icon-name>
        #    theme: <icon-theme>
        #    link: <link-url>
        github:
            name: github
            theme: brands
            link: https://github.com/xxxxxx
        bilibili:
            name: bilibili
            theme: brands
            link: https://space.bilibili.com/xxxxxx
